/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.pattern;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        // run app...        
    }

    
}
